apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      nodeSelector:
        kubernetes.io/hostname: worker2
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "FABRIC"
            - name: VERSION
              value: "1.21.1"
            - name: FABRIC_LOADER_VERSION
              value: "0.16.14"
          ports:
            - containerPort: 25565
          volumeMounts:
            - mountPath: /data
              name: minecraft-storage
      volumes:
        - name: minecraft-storage
          persistentVolumeClaim:
            claimName: minecraft-pvc
