apiVersion: apps/v1
kind: Deployment
metadata:
  name: playit-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playit
  template:
    metadata:
      labels:
        app: playit
    spec:
      containers:
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:latest
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit-secret
                  key: SECRET_KEY